/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PhysicalCertificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "evaluate"
      | "getProof"
      | "getUserEncryptedMetrics"
      | "hasMetrics"
      | "submitEncryptedMetrics"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evaluate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProof",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEncryptedMetrics",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMetrics",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedMetrics",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "evaluate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserEncryptedMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasMetrics", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedMetrics",
    data: BytesLike
  ): Result;
}

export interface PhysicalCertification extends BaseContract {
  connect(runner?: ContractRunner | null): PhysicalCertification;
  waitForDeployment(): Promise<this>;

  interface: PhysicalCertificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  evaluate: TypedContractMethod<[user: AddressLike], [string], "nonpayable">;

  getProof: TypedContractMethod<[user: AddressLike], [string], "view">;

  getUserEncryptedMetrics: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string, string, string] & {
        heartRate: string;
        bmi: string;
        bloodPressureSystolic: string;
        bloodPressureDiastolic: string;
        lungCapacity: string;
        bloodOxygen: string;
      }
    ],
    "view"
  >;

  hasMetrics: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  submitEncryptedMetrics: TypedContractMethod<
    [
      encryptedHeartRate: BytesLike,
      encryptedBMI: BytesLike,
      encryptedBPSystolic: BytesLike,
      encryptedBPDiastolic: BytesLike,
      encryptedLungCapacity: BytesLike,
      encryptedBloodOxygen: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evaluate"
  ): TypedContractMethod<[user: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserEncryptedMetrics"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string, string, string] & {
        heartRate: string;
        bmi: string;
        bloodPressureSystolic: string;
        bloodPressureDiastolic: string;
        lungCapacity: string;
        bloodOxygen: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasMetrics"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitEncryptedMetrics"
  ): TypedContractMethod<
    [
      encryptedHeartRate: BytesLike,
      encryptedBMI: BytesLike,
      encryptedBPSystolic: BytesLike,
      encryptedBPDiastolic: BytesLike,
      encryptedLungCapacity: BytesLike,
      encryptedBloodOxygen: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
